#!/bin/sh
xcursorgen left_ptr_watch.in ../cursors/left_ptr_watch
xcursorgen hand1.in ../cursors/hand1
xcursorgen hand2.in ../cursors/hand2
xcursorgen left_ptr.in ../cursors/left_ptr
#xcursorgen center_ptr.in ../cursors/center_ptr
xcursorgen xterm.in ../cursors/xterm
xcursorgen crossed_circle.in ../cursors/crossed_circle
xcursorgen right_ptr.in ../cursors/right_ptr
xcursorgen copy.in ../cursors/copy
xcursorgen move.in ../cursors/move
xcursorgen pointer-move.in ../cursors/pointer-move
xcursorgen link.in ../cursors/link
xcursorgen circle.in ../cursors/circle
xcursorgen sb_h_double_arrow.in ../cursors/sb_h_double_arrow
xcursorgen sb_v_double_arrow.in ../cursors/sb_v_double_arrow
xcursorgen top_left_corner.in ../cursors/top_left_corner
xcursorgen top_right_corner.in ../cursors/top_right_corner
xcursorgen bottom_left_corner.in ../cursors/bottom_left_corner
xcursorgen bottom_right_corner.in ../cursors/bottom_right_corner
xcursorgen fd_double_arrow.in ../cursors/fd_double_arrow
xcursorgen bd_double_arrow.in ../cursors/bd_double_arrow
xcursorgen watch.in ../cursors/watch
xcursorgen sb_left_arrow.in ../cursors/sb_left_arrow
xcursorgen sb_right_arrow.in ../cursors/sb_right_arrow
xcursorgen sb_up_arrow.in ../cursors/sb_up_arrow
xcursorgen sb_down_arrow.in ../cursors/sb_down_arrow
#xcursorgen based_arrow_down.in ../cursors/based_arrow_down
#xcursorgen based_arrow_up.in ../cursors/based_arrow_up
xcursorgen bottom_side.in ../cursors/bottom_side
xcursorgen top_side.in ../cursors/top_side
xcursorgen left_side.in ../cursors/left_side
xcursorgen right_side.in ../cursors/right_side
xcursorgen grabbing.in ../cursors/grabbing
xcursorgen question_arrow.in ../cursors/question_arrow
xcursorgen top_tee.in ../cursors/top_tee
xcursorgen bottom_tee.in ../cursors/bottom_tee
xcursorgen left_tee.in ../cursors/left_tee
xcursorgen right_tee.in ../cursors/right_tee
xcursorgen ul_angle.in ../cursors/ul_angle
xcursorgen ll_angle.in ../cursors/ll_angle
xcursorgen ur_angle.in ../cursors/ur_angle
xcursorgen lr_angle.in ../cursors/lr_angle
xcursorgen X_cursor.in ../cursors/X_cursor
#xcursorgen crosshair.in ../cursors/crosshair
xcursorgen crosshair.in ../cursors/cell
xcursorgen cross.in ../cursors/cross
xcursorgen tcross.in ../cursors/tcross
xcursorgen dotbox.in ../cursors/dotbox
xcursorgen plus.in ../cursors/plus
xcursorgen pencil.in ../cursors/pencil
xcursorgen dnd-none.in ../cursors/dnd-none
xcursorgen dnd-copy.in ../cursors/dnd-copy
xcursorgen dnd-link.in ../cursors/dnd-link
xcursorgen dnd-move.in ../cursors/dnd-move
xcursorgen dnd-ask.in ../cursors/dnd-ask
xcursorgen dnd-no-drop.in ../cursors/dnd-no-drop
xcursorgen zoom-in.in ../cursors/zoom-in
xcursorgen zoom-out.in ../cursors/zoom-out
xcursorgen all-scroll.in ../cursors/all-scroll
xcursorgen vertical-text.in ../cursors/vertical-text
xcursorgen context-menu.in ../cursors/context-menu
